export PS1='\[\033[01;32m\]\u@localhost\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

# for macOS
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

# for Ubuntu
export PATH="$HOME/.local/bin:$PATH"

# Initialize anyenv if installed
if [ -d $HOME/.anyenv ]
then
  export PATH="$HOME/.anyenv/bin:$PATH"
  eval "$(anyenv init -)"
fi

alias be="bundle exec"
