---
- homebrew:
    update_homebrew: yes

- homebrew:
    name: '{{item.name}}'
  with_items:
    - { name: bash-completion }
    - { name: git }

- file:
    state: link
    path: '{{ my_env_root }}/../Vagrantfile'
    src: '{{ my_env_root }}/files/local/Vagrantfile'
